"""Test suite for mojo-diff.

Opcode hand cases and unified-diff byte-equality are checked against fixtures
generated by Python's `difflib` (see `test/data/generate_fixtures.py`). Ratio
values are compared against `difflib.SequenceMatcher.ratio()` computed offline.
"""

from std.testing import assert_equal, assert_true, TestSuite
from std.time import perf_counter_ns

from diff import (
    OpCode,
    Match,
    splitlines_keepends,
    matching_blocks,
    get_opcodes,
    ratio,
    unified_diff,
)


# --- helpers ---------------------------------------------------------------


def _lines(*items: String) -> List[String]:
    var out = List[String]()
    for it in items:
        out.append(it.copy())
    return out^


def _assert_ops(
    got: List[OpCode], expected: List[OpCode], name: String
) raises:
    assert_equal(len(got), len(expected), name + ": opcode count")
    for i in range(len(expected)):
        assert_true(got[i] == expected[i], name + ": opcode " + String(i))


def _read(name: String) raises -> String:
    return open("test/data/" + name, "r").read()


def _reconstruct(a: List[String], b: List[String]) -> List[String]:
    """Rebuild `b` by applying `get_opcodes(a, b)` to `a`."""
    var ops = get_opcodes(a, b)
    var out = List[String]()
    for op in ops:
        if op.tag == "equal":
            for k in range(op.a_start, op.a_end):
                out.append(a[k].copy())
        elif op.tag == "delete":
            pass
        else:  # insert or replace -> take from b
            for k in range(op.b_start, op.b_end):
                out.append(b[k].copy())
    return out^


# --- opcode hand cases -----------------------------------------------------


def test_opcodes_replace_mid() raises:
    var a = _lines("a", "b", "c", "d")
    var b = _lines("a", "X", "c", "d")
    var exp = List[OpCode]()
    exp.append(OpCode(String("equal"), 0, 1, 0, 1))
    exp.append(OpCode(String("replace"), 1, 2, 1, 2))
    exp.append(OpCode(String("equal"), 2, 4, 2, 4))
    _assert_ops(get_opcodes(a, b), exp, "replace_mid")


def test_opcodes_insert() raises:
    var a = _lines("a", "c")
    var b = _lines("a", "b", "c")
    var exp = List[OpCode]()
    exp.append(OpCode(String("equal"), 0, 1, 0, 1))
    exp.append(OpCode(String("insert"), 1, 1, 1, 2))
    exp.append(OpCode(String("equal"), 1, 2, 2, 3))
    _assert_ops(get_opcodes(a, b), exp, "insert")


def test_opcodes_delete() raises:
    var a = _lines("a", "b", "c")
    var b = _lines("a", "c")
    var exp = List[OpCode]()
    exp.append(OpCode(String("equal"), 0, 1, 0, 1))
    exp.append(OpCode(String("delete"), 1, 2, 1, 1))
    exp.append(OpCode(String("equal"), 2, 3, 1, 2))
    _assert_ops(get_opcodes(a, b), exp, "delete")


def test_opcodes_append() raises:
    var a = _lines("a", "b")
    var b = _lines("a", "b", "c", "d")
    var exp = List[OpCode]()
    exp.append(OpCode(String("equal"), 0, 2, 0, 2))
    exp.append(OpCode(String("insert"), 2, 2, 2, 4))
    _assert_ops(get_opcodes(a, b), exp, "append")


def test_opcodes_prepend() raises:
    var a = _lines("c", "d")
    var b = _lines("a", "b", "c", "d")
    var exp = List[OpCode]()
    exp.append(OpCode(String("insert"), 0, 0, 0, 2))
    exp.append(OpCode(String("equal"), 0, 2, 2, 4))
    _assert_ops(get_opcodes(a, b), exp, "prepend")


def test_opcodes_identical() raises:
    var a = _lines("a", "b")
    var exp = List[OpCode]()
    exp.append(OpCode(String("equal"), 0, 2, 0, 2))
    _assert_ops(get_opcodes(a, a), exp, "identical")


def test_opcodes_disjoint() raises:
    var a = _lines("a", "b")
    var b = _lines("x", "y")
    var exp = List[OpCode]()
    exp.append(OpCode(String("replace"), 0, 2, 0, 2))
    _assert_ops(get_opcodes(a, b), exp, "disjoint")


def test_opcodes_empty_a() raises:
    var a = List[String]()
    var b = _lines("a", "b")
    var exp = List[OpCode]()
    exp.append(OpCode(String("insert"), 0, 0, 0, 2))
    _assert_ops(get_opcodes(a, b), exp, "empty_a")


def test_opcodes_empty_b() raises:
    var a = _lines("a", "b")
    var b = List[String]()
    var exp = List[OpCode]()
    exp.append(OpCode(String("delete"), 0, 2, 0, 0))
    _assert_ops(get_opcodes(a, b), exp, "empty_b")


def test_opcodes_both_empty() raises:
    var a = List[String]()
    var b = List[String]()
    assert_equal(len(get_opcodes(a, b)), 0, "both empty -> no opcodes")


def test_opcode_roundtrip() raises:
    # Applying opcodes to `a` must reproduce `b`.
    var a = _lines("a", "b", "c", "d", "e", "f")
    var b = _lines("a", "X", "c", "d", "Y", "Z", "f")
    var rebuilt = _reconstruct(a, b)
    assert_equal(len(rebuilt), len(b), "roundtrip length")
    for i in range(len(b)):
        assert_equal(rebuilt[i], b[i], "roundtrip line " + String(i))


# --- edit-distance cap / DoS guard -----------------------------------------


def test_cap_coarse_fallback() raises:
    # Shared prefix (2 lines) + a differing middle that has an internal match
    # ("MID") + shared suffix (2 lines). Under a tiny cap the exact search bails
    # out and the middle collapses to a single coarse `replace`, while the
    # shared prefix/suffix are still reported as `equal`.
    var a = _lines("p0", "p1", "a0", "MID", "a1", "s0", "s1")
    var b = _lines("p0", "p1", "b0", "MID", "b1", "s0", "s1")
    var coarse = get_opcodes(a, b, 2)
    var exp = List[OpCode]()
    exp.append(OpCode(String("equal"), 0, 2, 0, 2))
    exp.append(OpCode(String("replace"), 2, 5, 2, 5))
    exp.append(OpCode(String("equal"), 5, 7, 5, 7))
    _assert_ops(coarse, exp, "cap coarse fallback")
    # With headroom the same diff stays fine-grained (the internal "MID" match
    # is preserved), i.e. strictly more opcodes than the coarse form — proving
    # the cap does not degrade any diff whose edit distance is within it.
    var exact = get_opcodes(a, b, 100)
    assert_true(len(exact) > len(coarse), "sub-cap diff stays fine-grained")


def test_cap_bounds_dissimilar() raises:
    # Fully dissimilar inputs (no shared prefix/suffix): the capped search must
    # return a single coarse `replace` and terminate, instead of allocating the
    # O(D^2) Myers trace that would OOM on large unrelated files.
    var a = _lines("x0", "x1", "x2", "x3", "x4", "x5")
    var b = _lines("y0", "y1", "y2", "y3", "y4", "y5")
    var ops = get_opcodes(a, b, 2)
    var exp = List[OpCode]()
    exp.append(OpCode(String("replace"), 0, 6, 0, 6))
    _assert_ops(ops, exp, "cap dissimilar single replace")


# --- ratio -----------------------------------------------------------------


def test_ratio_identical() raises:
    assert_equal(ratio(_lines("a", "b", "c"), _lines("a", "b", "c")), 1.0)


def test_ratio_one_change() raises:
    assert_equal(
        ratio(_lines("a", "b", "c", "d"), _lines("a", "X", "c", "d")), 0.75
    )


def test_ratio_disjoint() raises:
    assert_equal(ratio(_lines("a", "b", "c"), _lines("x", "y", "z")), 0.0)


def test_ratio_empty_both() raises:
    assert_equal(ratio(List[String](), List[String]()), 1.0)


def test_ratio_one_empty() raises:
    assert_equal(ratio(_lines("a", "b"), List[String]()), 0.0)


def test_ratio_prefix() raises:
    assert_equal(
        ratio(_lines("a", "b", "c"), _lines("a", "b", "c", "d", "e")), 0.75
    )


def test_ratio_half() raises:
    var got = ratio(_lines("1", "2", "3", "4"), _lines("1", "2"))
    assert_true(abs(got - 0.6666666666666666) < 1e-12, "ratio half")


# --- unified diff byte-equality vs Python fixtures -------------------------


def _check_unified(name: String) raises:
    var a = _read(name + ".a.txt")
    var b = _read(name + ".b.txt")
    var expected = _read(name + ".unified.txt")
    assert_equal(unified_diff(a, b, "a", "b", 3), expected, name + " unified")


def test_unified_code_edit() raises:
    _check_unified("code_edit")


def test_unified_prose_edit() raises:
    _check_unified("prose_edit")


def test_unified_empty_to_content() raises:
    _check_unified("empty_to_content")


def test_unified_identical() raises:
    # difflib yields nothing (not even a header) for identical inputs.
    _check_unified("identical")
    var a = _read("identical.a.txt")
    assert_equal(unified_diff(a, a, "a", "b", 3), String(""), "identical empty")


def test_unified_total_rewrite() raises:
    _check_unified("total_rewrite")


def test_unified_no_newline_b() raises:
    _check_unified("no_newline_b")


def test_unified_no_newline_both() raises:
    _check_unified("no_newline_both")


def test_unified_content_to_empty() raises:
    _check_unified("content_to_empty")


def test_unified_multi_hunk() raises:
    _check_unified("multi_hunk")


def test_unified_one_line() raises:
    _check_unified("one_line")


def test_unified_context_param() raises:
    # context=1 must group differently (byte-match Python's n=1 output).
    var a = _read("multi_hunk.a.txt")
    var b = _read("multi_hunk.b.txt")
    var expected = _read("multi_hunk.n1.unified.txt")
    assert_equal(unified_diff(a, b, "a", "b", 1), expected, "multi_hunk n=1")


def test_unified_custom_filenames() raises:
    var got = unified_diff(
        String("x\n"), String("y\n"), "before.txt", "after.txt", 3
    )
    assert_true(
        got.startswith("--- before.txt\n+++ after.txt\n"), "custom filenames"
    )


# --- splitlines ------------------------------------------------------------


def test_splitlines_keepends() raises:
    var a = splitlines_keepends(String("a\nb\n"))
    assert_equal(len(a), 2, "trailing newline: 2 lines")
    assert_equal(a[0], "a\n", "keep terminator")
    assert_equal(a[1], "b\n", "keep terminator 2")
    var b = splitlines_keepends(String("a\nb"))
    assert_equal(len(b), 2, "no trailing newline: 2 lines")
    assert_equal(b[1], "b", "last line no terminator")
    assert_equal(len(splitlines_keepends(String(""))), 0, "empty -> 0 lines")


# --- performance -----------------------------------------------------------


def test_perf_5k() raises:
    # Two 5,000-line files with scattered edits (~1 in 50 lines changed).
    var a = List[String]()
    var b = List[String]()
    for i in range(5000):
        a.append("line " + String(i) + " of the file\n")
        if i % 50 == 0:
            b.append("CHANGED line " + String(i) + " of the file\n")
        else:
            b.append("line " + String(i) + " of the file\n")
    var start = perf_counter_ns()
    var ops = get_opcodes(a, b)
    var elapsed_ns = perf_counter_ns() - start
    var elapsed_ms = Float64(elapsed_ns) / 1.0e6
    print("  [perf] 5k-line diff:", elapsed_ms, "ms,", len(ops), "opcodes")
    assert_true(len(ops) > 0, "5k diff produced opcodes")
    # 100 changed lines -> replace opcodes interleaved with equal runs.
    var replaces = 0
    for op in ops:
        if op.tag == "replace":
            replaces += 1
    assert_equal(replaces, 100, "5k diff replace-opcode count")


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
